name: release-and-page
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
    paths-ignore:
      # - 'README.md'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

concurrency:
  group: release-ci-group
  cancel-in-progress: false

jobs:
  release-and-page:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          # cache: yarn

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: Install Dependency
        # run: yarn global add tiddlywiki
        run: yarn install

      - name: Build Neotw
        run: |
          npm run build:oeyoews

        # - name: Create Release
        #   uses: softprops/action-gh-release@v1
        #   if: startsWith(github.ref, 'refs/tags/')
        #   # if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name != 'nightly')
        #   # https://github.com/neovim/neovim/blob/234b8c5f3d57294dda06dbc6c1760e5983bd2c19/.github/workflows/release.yml#L264
        #   with:
        #     files: |
        #       dist/plugins/*.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: |
            ./dist

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release

      # - uses: jsmrcaga/action-netlify-deploy@v2.0.0
      #   with:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_DEPLOY_TO_PROD: true
      #     NETLIFY_SITE_ID: 7654bd58-2df9-4962-9a81-4cca9cf78b9c
      #     build_directory: ./dist
      #     NETLIFY_DEPLOY_MESSAGE: 'Deployed from GitHub action'
      #     install_command: 'echo Skipping installing the dependencies'
      #     build_command: 'echo Skipping building the web files'
